config/routes.rb
Rails.application.routes.draw do
  resources :speedtests
  resources :charts

end

app/models/speedtest.rb
class Speedtest < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index

    @speedtests = Speedtest.all
  end
end

app/controllers/speedtests_controller.rb
class SpeedtestsController < ApplicationController
  before_action :set_speedtest, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /speedtests
  # GET /speedtests.json
  def index

    @speedtests = Speedtest.all.order(:created_at).reverse
  end

  # GET /speedtests/1
  # GET /speedtests/1.json
  def show
  end

  # GET /speedtests/new
  def new
    @speedtest = Speedtest.new
  end

  # GET /speedtests/1/edit
  def edit
  end

  # POST /speedtests
  # POST /speedtests.json
  def create
    @speedtest = Speedtest.new(speedtest_params)

    respond_to do |format|
      if @speedtest.save
        format.html { redirect_to @speedtest, notice: 'Speedtest was successfully created.' }
        format.json { render :show, status: :created, location: @speedtest }
      else
        format.html { render :new }
        format.json { render json: @speedtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speedtests/1
  # PATCH/PUT /speedtests/1.json
  def update
    respond_to do |format|
      if @speedtest.update(speedtest_params)
        format.html { redirect_to @speedtest, notice: 'Speedtest was successfully updated.' }
        format.json { render :show, status: :ok, location: @speedtest }
      else
        format.html { render :edit }
        format.json { render json: @speedtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speedtests/1
  # DELETE /speedtests/1.json
  def destroy
    @speedtest.destroy
    respond_to do |format|
      format.html { redirect_to speedtests_url, notice: 'Speedtest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speedtest
      @speedtest = Speedtest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speedtest_params
      params.permit(:ssid, :ping, :upload, :download, :hostname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/speedtests_helper.rb
module SpeedtestsHelper
end

app/views/charts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Speedtests</h1>

<%= column_chart Speedtest.group_by_hour(:created_at).count %>


<br>

<!-- <%= link_to 'New Speedtest', new_speedtest_path %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Speedy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/speedtests/_form.html.erb
<%= form_for(@speedtest) do |f| %>
  <% if @speedtest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@speedtest.errors.count, "error") %> prohibited this speedtest from being saved:</h2>

      <ul>
      <% @speedtest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ssid %><br>
    <%= f.text_field :ssid %>
  </div>
  <div class="field">
    <%= f.label :ping %><br>
    <%= f.text_field :ping %>
  </div>
  <div class="field">
    <%= f.label :upload %><br>
    <%= f.text_field :upload %>
  </div>
  <div class="field">
    <%= f.label :download %><br>
    <%= f.text_field :download %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/speedtests/edit.html.erb
<h1>Editing Speedtest</h1>

<%= render 'form' %>

<%= link_to 'Show', @speedtest %> |
<%= link_to 'Back', speedtests_path %>

app/views/speedtests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Speedtests</h1>

<table>
  <thead>
    <tr>
      <th>Hostname</th>
      <th>Ssid</th>
      <th>Ping</th>
      <th>Upload</th>
      <th>Download</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speedtests.each do |speedtest| %>
      <tr>
        <td><%= speedtest.hostname %></td>
        <td><%= speedtest.ssid %></td>
        <td><%= speedtest.ping %></td>
        <td><%= speedtest.upload %></td>
        <td><%= speedtest.download %></td>
        <td><%= speedtest.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Speedtest', new_speedtest_path %> -->

app/views/speedtests/new.html.erb
<h1>New Speedtest</h1>

<%= render 'form' %>

<%= link_to 'Back', speedtests_path %>

app/views/speedtests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ssid:</strong>
  <%= @speedtest.ssid %>
</p>

<p>
  <strong>Ping:</strong>
  <%= @speedtest.ping %>
</p>

<p>
  <strong>Upload:</strong>
  <%= @speedtest.upload %>
</p>

<p>
  <strong>Download:</strong>
  <%= @speedtest.download %>
</p>

<%= link_to 'Edit', edit_speedtest_path(@speedtest) %> |
<%= link_to 'Back', speedtests_path %>